crs_dir      = "./coreruleset/rules/"
crs_ids_path = "./data/crs_sqli_ids_4.0.0.json"
models_path  = "./data/models/"
figures_path = './data/figures/'
dataset_path = './data/dataset/'

[params]
paranoia_levels = [1, 2, 3, 4]
linear_models   = ['svc', 'log_reg']
models          = ['rf', 'modsec']
penalties       = ['l1', 'l2']